config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'

  devise_for :users
  get '/feeds', to: 'feeds#index'
  get '/feeds/new', to: 'feeds#new'
  post '/feeds', to: 'feeds#create'
  delete '/feeds/:id', to: 'feeds#destroy'
  post '/feeds/:id/comments', to: 'feeds#create_comment'
  delete '/feeds/:id/comments/:comment_id', to: 'feeds#destroy_comment'
  get '/feeds/:id/like', to: 'feeds#like'
  post '/feed_comments/:id', to: 'feeds#create_recomment'

  get '/events', to: 'events#index'
  get '/events/new', to: 'events#new'
  post '/events', to: 'events#create'
  delete '/events/:id', to: 'events#destroy'
  post '/events/:id/comments', to: 'events#create_comment'
  delete '/events/:id/comments/:comment_id', to: 'events#destroy_comment'

  get '/follows/:followed_id', to: 'follows#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_comments, dependent: :destroy

  # Users : EventComments : Events  M:N Relations
  # commenting_user의 중복을 막을 때 아래와 같이 할 수 있음
  # has_many :commenting_users, -> { distinct }, through: :event_comments, source: :user
  has_many :commenting_users, through: :event_comments, source: :user
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user
  has_many :feed_comments
end

app/models/feed_comment.rb
class FeedComment < ApplicationRecord
  belongs_to :user
  belongs_to :feed
  has_many :feed_recomments
end

app/models/feed_like.rb
class FeedLike < ApplicationRecord
  # Users : FeedLikes : Feeds M:N Relations
  belongs_to :user
  belongs_to :feed
end

app/models/feed_recomment.rb
class FeedRecomment < ApplicationRecord
  belongs_to :feed_comment
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :followed, class_name: :User#, foreign_key: :followed_id
  belongs_to :follower, class_name: :User#, foreign_key: :follower_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds
  has_many :feed_comments

  has_many :events
  has_many :event_comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = Event.all
    render 'index'
  end

  def new
    render 'new'
  end

  def create
    date = params[:date]
    title = params[:title]

    event = Event.new
    event.date = date
    event.title = title
    event.user_id = current_user.id
    event.save

    redirect_to action: 'index'
  end

  def destroy
    event_id = params[:id]
    Event.destroy(event_id)

    redirect_to action: 'index'
  end

  def create_comment
    event_id = params[:id]
    content = params[:content]

    event = Event.find(event_id)
    new_comment = event.event_comments.new
    new_comment.content = content
    new_comment.user_id = current_user.id
    new_comment.save

    redirect_to action: 'index'
  end

  def destroy_comment
    comment_id = params[:comment_id]
    EventComment.destroy(comment_id)

    redirect_to action: 'index'
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!
  def index
    @feeds = Feed.all
    render 'index'
  end

  def new
    render 'new'
  end

  def create
    title = params[:title]
    content = params[:content]

    feed = Feed.new
    feed.title = title
    feed.content = content
    feed.user_id = current_user.id
    feed.save

    redirect_to action: 'index'
  end

  def destroy
    feed_id = params[:id]
    Feed.destroy(feed_id)

    redirect_to action: 'index'
  end

  def create_comment
    feed_id = params[:id]
    content = params[:content]

    feed = Feed.find(feed_id)
    new_comment = feed.feed_comments.new
    new_comment.content = content
    new_comment.user_id = current_user.id 
    new_comment.save
=begin
동일한 일을 하는 코드
    new_comment = FeedComment.new
    new_comment.feed_id = feed_id
    new_comment.content = content
    new_comment.save
=end

    redirect_to action: 'index'
  end

  def destroy_comment
    comment_id = params[:comment_id]
    FeedComment.destroy(comment_id)

    #redirect_to action: 'index'
    render json: {}
  end

  def like
    feed_like_hash = {user_id: current_user.id, feed_id: params[:id]}
    # 아래 두 코드는 같음
    # like = FeedLike.where(user_kd: current_user.id, feed_id: params[:id])
    like = FeedLike.where(feed_like_hash)
    if like.empty?
      FeedLike.create(feed_like_hash)
    else
      like.destroy_all
    end

    redirect_to action: 'index'
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    receiver = User.find(params[:followed_id])
    current_user.request_follow(receiver)

    # 다른 page에서도 follow 쓰려면
    # redirect_back(fallback_location: root_path)과 같이 변경
    redirect_to controller: 'feeds', action: 'index'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    'mdl-navigation__link--current' if request.path == test_path
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

     messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join
     sentence = I18n.t('errors.messages.not_saved',
     count: resource.errors.count,
     resource: resource.class.model_name.human.downcase)

     html = <<-HTML
     <p>
      <br>
      #{messages}
      <br>
     </p>
     HTML

     html.html_safe
  end
end

# <div class="mdl-js-snackbar mdl-snackbar mdl-snackbar--active"
#   data-upgraded=",MaterialSnackbar">
#    <div class="mdl-snackbar__text left-align">
#      #{messages}
#    </div>
#    <button class="mdl-snackbar__action">
#      <strong>닫기</strong>
#    </button>
#  </div>

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- SEO -->
    <title>Likenew</title>
    <meta name="description" content="설명을 적으세요 (160자 이내)">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://example.com/page.html">
    <meta property="og:title" content="Content Title">
    <meta property="og:image" content="https://example.com/image.jpg">
    <meta property="og:description" content="Description Here">
    <meta property="og:site_name" content="Site Name">
    <meta property="og:locale" content="en_US">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@site_account">
    <meta name="twitter:creator" content="@individual_account">
    <meta name="twitter:url" content="https://example.com/page.html">
    <meta name="twitter:title" content="Content Title">
    <meta name="twitter:description" content="Content description less than 200 characters">
    <meta name="twitter:image" content="https://example.com/image.jpg">
    <!-- Favicons -->
  <!--
    <link rel="icon" type="image/png" href="https://example.com/favicon.png">
    <link rel="apple-touch-icon" href="/custom-icon.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="msapplication-config" content="browserconfig.xml" />
  -->
    <!-- Avoid Duplicate Content -->
    <link rel="canonical" href="http://example.com/2017/09/a-new-article-to-read.html">
    <!-- Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Stylesheets & Javascripts -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  </head>

  <body class="mdl-color--grey-50">
    <% if !user_signed_in? %>
    <!-- Layout : 비회원 -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <!-- Header -->
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row signed-out">
          <span class="mdl-layout-title">Likenew</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/users/sign_in">로그인</a>
            <a class="mdl-navigation__link" href="/users/sign_up">회원가입</a>
          </nav>
        </div>
      </header>

    <% else %>
    <!-- Layout : 회원 -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <!-- Header -->
      <header class="mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title"><%= controller_name %></span>
          <div class="mdl-layout-spacer"></div>
          <!-- Menu -->
          <button id="account-menu" class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">account_circle</i>
          </button>
          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="account-menu">
            <li disabled class="mdl-menu__item"><%= current_user.name %>님</li>
            <%= link_to '내 계정', '/users/edit', :class => 'mdl-menu__item' %>
            <%= link_to '로그아웃', '/users/sign_out', method: :delete, :class => 'mdl-menu__item' %>
          </ul>
        </div>
      </header>
      <!-- Drawer -->
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>
        <nav class="mdl-navigation">
           <%= link_to "피드", feeds_path, :class => ["mdl-navigation__link", current_class?(feeds_path)].join(" ") %>
          <%= link_to "이벤트", events_path, :class => ["mdl-navigation__link", current_class?(events_path)].join(" ") %>
          <hr>
        </nav>
        <!-- User List -->
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link mdl-navigation__link--disabled pt-0 pb-0">유저 (<%= User.count %>명)</a>
          <div class="mdl-list">
            <% User.all.each do |u| %>
            <% if u == current_user %>
              <!-- 본인 -->
              <div class="mdl-list__item mdl-list__item--two-line">
                <span class="mdl-list__item-primary-content">
                  <i class="material-icons mdl-list__item-avatar">person</i>
                  <strong><%= u.name %></strong>
                  <span class="mdl-list__item-sub-title">팔로잉 <%= current_user.followings.size %> 팔로워 <%= current_user.followers.size %></span>
                </span>
              </div>
            <% else %>
              <!-- 타인 -->
              <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                  <i class="material-icons mdl-list__item-avatar">person</i>
                  <span><%= u.name %></span>
                </span>
                <% if current_user.followings.include? u %>
                  <a class="mdl-list__item-secondary-action">
                    <i class="material-icons">person_add</i>
                  </a>
                <% else %>
                  <%=link_to "/follows/#{u.id}", method: :get, :class => "mdl-list__item-secondary-action mdl-color-text--grey-500" do %>
                    <i class="material-icons">person_add</i>
                  <% end %>
                <% end %>
              </div>
            <% end %>
            <% end %>
          </div>
        </nav>
      </div>
    <% end %>

      <!-- Content -->
      <main class="mdl-layout__content">
        <div class="page-content"><%= yield %></div>
      </main>
    </div>
        
    <%= link_to 'Sign out', '/users/sign_out', method: :delete  %>
  </body>
</html>